version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "deps" 
    pull-request-branch-name:
      prefix: "dependabot"
    labels:
      - "dependencies"
    groups:
      minor-and-patch:
        patterns:
          - '*'
        dependency-type: all
        update-types:
          - 'version-update:semver-minor'
          - 'version-update:semver-patch'
