version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - "dependencies"
    groups:
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
    open-pull-requests-limit: 25
