services:
  postgres:
    image: postgres:15.4
    container_name: database
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  openapi-generator:
    container_name: openapi-generator
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.openapi
    volumes:
      - ./:/local
      - ./scripts:/scripts

volumes:
  postgres_data: