name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yaml