on: [workflow_call]

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Generate Prisma client
      run: pnpm run prisma:generate

    - name: Run tests api
      run: pnpm run test:api

    - name: Run tests e2e
      run: pnpm run test:api:e2e

    - name: Run client tests
      run: pnpm run test:client
